spring.application.name=Resturant_Backend

SPRING_DATASOURCE_URL=jdbc:mysql://root:muUCIHJBPXmjIhDLKLCwzdMgHalVowMB@junction.proxy.rlwy.net:52525/railway
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=muUCIHJBPXmjIhDLKLCwzdMgHalVowMB

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

